services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: web-echo-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./resources/keycloak/web-echo-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8081:8080"
